/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 .\public\models\pipe.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/pipe.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube004.geometry} material={materials['Material.007']} position={[1.35, -13.13, 0]} scale={[0.05, 9, 0.12]} />
      <mesh geometry={nodes.Cube011.geometry} material={materials['Material.009']} position={[-0.55, -13.13, 0]} scale={[0.05, 9, 0.12]} />
      <mesh geometry={nodes.Cube012.geometry} material={materials['Material.010']} position={[-1.15, -13.13, 0]} scale={[0.05, 9, 0.12]} />
      <mesh geometry={nodes.Cube026.geometry} material={materials['Material.011']} position={[0.75, -13.13, 0]} scale={[0.05, 9, 0.12]} />
      <mesh geometry={nodes.Cube029.geometry} material={materials['Material.012']} position={[0.95, -13.13, 0]} scale={[0.05, 9, 0.12]} />
      <mesh geometry={nodes.Cube001.geometry} material={materials['Material.007']} position={[-1.35, 13.13, 0]} rotation={[0, 0, Math.PI]} scale={[0.05, 9, 0.12]} />
      <mesh geometry={nodes.Cube002.geometry} material={materials['Material.009']} position={[0.55, 13.13, 0]} rotation={[0, 0, Math.PI]} scale={[0.05, 9, 0.12]} />
      <mesh geometry={nodes.Cube003.geometry} material={materials['Material.010']} position={[1.15, 13.13, 0]} rotation={[0, 0, Math.PI]} scale={[0.05, 9, 0.12]} />
      <mesh geometry={nodes.Cube005.geometry} material={materials['Material.011']} position={[-0.75, 13.13, 0]} rotation={[0, 0, Math.PI]} scale={[0.05, 9, 0.12]} />
      <mesh geometry={nodes.Cube006.geometry} material={materials['Material.012']} position={[-0.95, 13.13, 0]} rotation={[0, 0, Math.PI]} scale={[0.05, 9, 0.12]} />
      <mesh geometry={nodes.collider001.geometry} material={nodes.collider001.material} position={[0, 3.33, 0]} scale={[1.5, 0.8, 0.14]} />
      <mesh geometry={nodes.collider.geometry} material={nodes.collider.material} position={[0, -3.33, 0]} scale={[1.5, 0.8, 0.14]} />
    </group>
  )
}

useGLTF.preload('/pipe.glb')
